### ISSUE TITLE
Feature request: ability to supply custom serializer

### ISSUE THREAD

**Issue by et1975** [zalmoxisus/remotedev#6]
With fable-compiler/fable-elmish/#18 adding a basic support for time-traveling debugging, I think I'll see reports of serialization problems from people trying to use it. The issue is F# adds certain features to the plain JS objects that don't survive the state roundtrip. 
I'm mitigating the issue to a degree with an internal/provisional Fable features, but it would be really nice to just be able to do my own serialization.
Thank you!

**Comment by zalmoxisus** [comment]
That's something we need here for sure. I've just [introduced a new parameter `serialize` for the Extension](https://github.com/zalmoxisus/redux-devtools-extension/releases), but it's available only for Redux for now.

Will specifying a custom [JSON `replacer` function](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#The_replacer_parameter) and [JSON `reviver` function](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse#Using_the_reviver_parameter) be enough? You'll be able also to provide a custom notation to identify a custom type in the monitor (like [we do for ImmutableJS](https://github.com/zalmoxisus/remotedev-serialize/blob/master/immutable/serialize.js)).

**Comment by et1975** [comment]
"reviving" is sort of what I'm doing right now, but it's a stop-gap and it doesn't cover some core F# types. On the other hand, full serialization already works for 99% of what people may want, but I don't think we could use it for revival. /cc @alfonsogarciacaro

**Comment by zalmoxisus** [comment]
I think you're able to use it for any data. See [how we do it for ImmutableJS](https://github.com/zalmoxisus/remotedev-serialize/blob/master/test/immutable.spec.js). So basically you mark a custom data in the [stringify replacer](https://github.com/zalmoxisus/remotedev-serialize/blob/master/immutable/serialize.js#L8-L20), then convert them back in the [parse reviver](https://github.com/zalmoxisus/remotedev-serialize/blob/master/immutable/serialize.js#L22-L39).

Also you could [send / receive data outside of JavaScript](https://github.com/zalmoxisus/remotedev-server/blob/v0.3/docs/API/Realtime.md#websocket-clients).

**Comment by alfonsogarciacaro** [comment]
Sorry, I haven't been following your progress very closely so I'm not aware of all details but I guess being able to provide a custom JSON (de)serializer should solve the problem. Fable injects generic info in the call to the deserializer but this can be probably wrapped in a closure or be solved in any other way (it's also possible to include the type info in the JSON).

About the data visualization, Fable serializer is designed to make the JSON quite readable (even more than the actual runtime representation) so I guess it can be used as is. But we can also study how to provide a custom replacer/reviver for each type.

**Comment by zalmoxisus** [comment]
I finally found some time time to update the API and docs for the extension.

So, now you can provide [a custom `serialize` option](http://extension.remotedev.io/docs/API/Arguments.html#serialize). You can even provide there your custom types for [a nice preview](https://cloud.githubusercontent.com/assets/7957859/21814330/a17d556a-d761-11e6-85ef-159dd12f36c5.png).

Also you can specify which [features to enable](http://extension.remotedev.io/docs/API/Arguments.html#features). Setting `import` to `true` (instead of `'custom'` which is by default) will load the history directly into the extension UI (as you suggested in https://github.com/zalmoxisus/redux-devtools-extension/issues/284). Setting `export` to `'custom'` (instead of `true` which is by default), will request data from the client part to be downloaded (instead of serializing data from the monitor part).

The options are available only for the extension, not for `remotedev` yet. After `3.0`, we'll split the API into a separate lib to reuse it here.

**Comment by et1975** [comment]
Awesome, I'll check it out!

**Comment by et1975** [comment]
I think we are good, thank you!
